"""
Alert domain entity for intelligent alerting.

Pure Python domain entity with no external dependencies.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Optional


class AlertType(str, Enum):
    """Types of security alerts."""

    NEW_CRITICAL_CVE = "NEW_CRITICAL_CVE"
    NEW_HIGH_CVE = "NEW_HIGH_CVE"
    EMERGING_THREAT = "EMERGING_THREAT"
    IOC_DETECTED = "IOC_DETECTED"
    TOPIC_TRENDING = "TOPIC_TRENDING"
    CORRELATION_FOUND = "CORRELATION_FOUND"
    ANOMALY_DETECTED = "ANOMALY_DETECTED"


class AlertSeverity(str, Enum):
    """Alert severity levels."""

    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"
    INFO = "INFO"


class AlertStatus(str, Enum):
    """Alert lifecycle status."""

    NEW = "NEW"
    ACKNOWLEDGED = "ACKNOWLEDGED"
    IN_PROGRESS = "IN_PROGRESS"
    RESOLVED = "RESOLVED"
    FALSE_POSITIVE = "FALSE_POSITIVE"
    IGNORED = "IGNORED"


@dataclass
class Alert:
    """
    Security alert entity.

    Represents an intelligent alert generated by the system.
    """

    alert_id: str  # Unique identifier
    alert_type: AlertType
    severity: AlertSeverity
    title: str
    description: str
    created_at: datetime
    status: AlertStatus = AlertStatus.NEW
    source_entity_type: str = ""  # "CVE", "ThreatIntel", "IOC", "Topic"
    source_entity_id: str = ""  # ID of the entity that triggered the alert
    related_cves: list[str] = field(default_factory=list)
    related_iocs: list[str] = field(default_factory=list)
    related_topics: list[str] = field(default_factory=list)
    tags: list[str] = field(default_factory=list)
    actionable_items: list[str] = field(default_factory=list)  # Recommended actions
    confidence_score: float = 0.0  # 0.0-1.0
    acknowledged_at: Optional[datetime] = None
    acknowledged_by: Optional[str] = None
    resolved_at: Optional[datetime] = None
    resolved_by: Optional[str] = None
    resolution_notes: str = ""
    notification_sent: bool = False
    metadata: dict[str, object] = field(default_factory=dict)

    def __post_init__(self) -> None:
        """Validate alert data."""
        if not self.alert_id:
            raise ValueError("Alert ID cannot be empty")
        if not self.title:
            raise ValueError("Alert title cannot be empty")
        if not self.description:
            raise ValueError("Alert description cannot be empty")
        if not 0.0 <= self.confidence_score <= 1.0:
            raise ValueError(
                f"Confidence score must be between 0.0 and 1.0, got {self.confidence_score}"
            )

    @property
    def is_active(self) -> bool:
        """Check if alert is active (not resolved/ignored)."""
        return self.status not in (
            AlertStatus.RESOLVED,
            AlertStatus.FALSE_POSITIVE,
            AlertStatus.IGNORED,
        )

    @property
    def is_critical(self) -> bool:
        """Check if alert is critical severity."""
        return self.severity == AlertSeverity.CRITICAL

    @property
    def is_high_severity(self) -> bool:
        """Check if alert is high or critical severity."""
        return self.severity in (AlertSeverity.CRITICAL, AlertSeverity.HIGH)

    @property
    def is_acknowledged(self) -> bool:
        """Check if alert has been acknowledged."""
        return self.status != AlertStatus.NEW

    @property
    def is_resolved(self) -> bool:
        """Check if alert has been resolved."""
        return self.status in (AlertStatus.RESOLVED, AlertStatus.FALSE_POSITIVE)

    @property
    def age_hours(self) -> float:
        """Get alert age in hours."""
        return (datetime.utcnow() - self.created_at).total_seconds() / 3600

    @property
    def is_high_confidence(self) -> bool:
        """Check if alert has high confidence (>= 0.8)."""
        return self.confidence_score >= 0.8

    def acknowledge(self, acknowledged_by: str) -> None:
        """
        Acknowledge the alert.

        Args:
            acknowledged_by: User or system that acknowledged the alert
        """
        if self.status == AlertStatus.NEW:
            self.status = AlertStatus.ACKNOWLEDGED
            self.acknowledged_at = datetime.utcnow()
            self.acknowledged_by = acknowledged_by

    def resolve(self, resolved_by: str, notes: str = "") -> None:
        """
        Resolve the alert.

        Args:
            resolved_by: User or system that resolved the alert
            notes: Resolution notes
        """
        if self.is_active:
            self.status = AlertStatus.RESOLVED
            self.resolved_at = datetime.utcnow()
            self.resolved_by = resolved_by
            self.resolution_notes = notes

    def mark_false_positive(self, marked_by: str, notes: str = "") -> None:
        """
        Mark alert as false positive.

        Args:
            marked_by: User who marked it as false positive
            notes: Explanation notes
        """
        if self.is_active:
            self.status = AlertStatus.FALSE_POSITIVE
            self.resolved_at = datetime.utcnow()
            self.resolved_by = marked_by
            self.resolution_notes = notes

    def to_dict(self) -> dict[str, object]:
        """Convert alert to dictionary."""
        return {
            "alert_id": self.alert_id,
            "alert_type": self.alert_type.value,
            "severity": self.severity.value,
            "title": self.title,
            "description": self.description,
            "created_at": self.created_at.isoformat(),
            "status": self.status.value,
            "source_entity_type": self.source_entity_type,
            "source_entity_id": self.source_entity_id,
            "related_cves": self.related_cves,
            "related_iocs": self.related_iocs,
            "related_topics": self.related_topics,
            "tags": self.tags,
            "actionable_items": self.actionable_items,
            "confidence_score": self.confidence_score,
            "acknowledged_at": self.acknowledged_at.isoformat() if self.acknowledged_at else None,
            "acknowledged_by": self.acknowledged_by,
            "resolved_at": self.resolved_at.isoformat() if self.resolved_at else None,
            "resolved_by": self.resolved_by,
            "resolution_notes": self.resolution_notes,
            "notification_sent": self.notification_sent,
            "age_hours": self.age_hours,
        }

    def __str__(self) -> str:
        """String representation."""
        return f"[{self.severity.value}] {self.title} ({self.status.value})"
